exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Session.vim
markdown: kramdown
timezone: America/New_York
title: ryanjhouston.com
author: Ryan Houston
description: Software development, homebrewing, and life that happens in between.
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
  -
    scope:
      path: "brewing"
    values:
      layout: "brew"
collections:
  recipes:
    output: true
gems:
  - jekyll-avatar
