version: '3'
services:
  site:
    image: jekyll/jekyll:latest
    command: jekyll server --drafts
    environment:
      - "JEKYLL_UID=${UID}"
      - "JEKYLL_GID=${GID}"
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
    volumes:
      - .:/srv/jekyll
